// GENERATED by tools/build_iconfont.py — do not edit by hand.
// Maps each icon name to its private-use codepoint char.
// `o` = outline glyph, `s` = solid (filled) glyph.
export interface GlyphPair { o: string; s: string }
export const GLYPHS: Record<string, GlyphPair> = {
  brief: { o: '\ue000', s: '\ue000' },
  star: { o: '\ue001', s: '\ue002' },
  wallet: { o: '\ue003', s: '\ue003' },
  bell: { o: '\ue004', s: '\ue005' },
  flame: { o: '\ue006', s: '\ue007' },
  chevron: { o: '\ue008', s: '\ue008' },
  chevronDown: { o: '\ue009', s: '\ue009' },
  back: { o: '\ue00a', s: '\ue00a' },
  plus: { o: '\ue00b', s: '\ue00b' },
  check: { o: '\ue00c', s: '\ue00c' },
  bookmark: { o: '\ue00d', s: '\ue00e' },
  search: { o: '\ue00f', s: '\ue00f' },
  calc: { o: '\ue010', s: '\ue010' },
  arrow: { o: '\ue011', s: '\ue011' },
  sparkle: { o: '\ue012', s: '\ue013' },
  bolt: { o: '\ue014', s: '\ue015' },
}
